### ISSUE TITLE
bootstrap4-util wrong filename?

### ISSUE THREAD

**Issue by creisi23** [gtbu/Typesetter-5.3-p8#9]
In line 571 of include/tool/Output/Combine.php the following file is included:
/include/thirdparty/Bootstrap4/js/util.min.js
But in include/thirdparty/Bootstrap4/js/ the file is called util**s**.min.js

**Comment by gtbu** [comment]
Yes - also in Tp5.2. If  Jshrink is active for $scripts  then it is omitted.  
I have another problem with scssphp and the Bootstrap4-template : The compiler v1.11 is running. But Mr. Krausz has added the vendor prefixes manually to the Bootstrap4-scss-files, and i get errors with px -> rem which should not be in bootstrap4 . The reason is unclear and i plan to update to Bootstrap 4.53 for which i have some vendor prefixes, the main reason for the long delay.  So i published a bstrap5-template for waiting users.
